app:
  host: localhost
  corsOrigin:
    - '*'
  port: 3000
  https: false

log:
  level: debug
  capture_request: true
  # NOTE : 요청에 대한 디버깅?
  capture_response: true
  # NOTE : 응답에 대한 디버깅 ?

  cloudwatch:
    enabled: false
    name: 
    log_group: 
    stream_name: 
    access_key: 
    secret_key: 
    log_level: debug

db:
  host: 
  username: 
  password: 
  port: 
  schema: 
